version: '3.8'

services:
  api:
    build: .
    container_name: petcompare_api
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run.py
